### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by SenthilCaesar** [pnlbwh/dMRIharmonization#4] opened 2019-04-23 11:37 UTC
./pipeline_test.sh
Harmonization completed
 IITmean_FA_skeleton.nii.gz file not found error
I tried to download the data, but its downloading IITmean_FA.nii.gz file

**Comment by tashrifbillah** [comment] 2019-04-23 14:08
As we saw, due to network problem, the file can't be downloaded in your computer. So, I have copied the file in `/tmp/IIT_mean_FA_skeleton.nii.gz`. Copy the file in `IITAtlas/` directory and then run test with previous outputs:

```
cd lib/tests/connectom_prisma/ \
../../harmonization.py \
--template ./template/ \
--ref_list connectom.txt.modified \
--tar_list prisma.txt \
--harm_list prisma.txt.modified.harmonized \
--ref_name CONNECTOM \
--tar_name PRISMA \
--nshm 4 \
--nproc -1 \
--debug
```

@SenthilCaesar , let me know how it goes.

**Comment by SenthilCaesar** [comment] 2019-04-23 14:35
I ran the above command
Traceback (most recent call last):
  File "/rfanfs/pnl-zorro/home/sq566/Downloads/conda/envs/dMRIharmonization/lib/python3.6/site-packages/nibabel/loadsave.py", line 40, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/sq566/dMRIharmonization/lib/tests/connectom_prisma/prisma/A/dti/**dwi_A_prisma_st_b1200_InMNI_FA.nii.gz**'

I checked inside the directory for the file name and its not there

**Comment by tashrifbillah** [comment] 2019-04-23 19:32
Hi @SenthilCaesar , I ran the debug test starting from your output. However, I couldn't reproduce the error. The only thing I realized was, `antsRegistration` didn't run correctly. I re-ran the registration and now the results are as expected:

```
Printing statistics :
CONNECTOM mean FA:  0.6799283760230598
PRISMA mean FA before harmonization:  0.8020249146122524
PRISMA mean FA after harmonization:  0.6374742090078741
```

Anyways, can you run the [unittests](https://github.com/pnlbwh/dMRIharmonization/tree/save-nifti#2-unittest) one last time? We just completed the whole pipeline test. Running unittests should need 5 minutes.

**Comment by tashrifbillah** [comment] 2019-04-23 20:09
Fixed by https://github.com/pnlbwh/dMRIharmonization/commit/f2e3d3da2d736b595180729ad7dbfd074aff015a

**Comment by tashrifbillah** [comment] 2019-04-23 20:37
Tests ran fine!

**Closed by tashrifbillah** 2019-04-23 20:37 UTC
